### ISSUE TITLE
RazorGenerator.MsBuild 2.4.1 -> 2.4.4 "Illegal Characters in path"

### ISSUE THREAD

**Issue by tbertenshaw** [RazorGenerator/RazorGenerator#99]
After upgrading my Asp.Net MVC 5.2  solution's  `RazorGenerator.MsBuild`  nuget package from 2.4.1 to 2.4.4 i get a build error

`4>C:\MYSOLUTIONPATH\packages\RazorGenerator.MsBuild.2.4.4\build\RazorGenerator.MsBuild.targets(41,9): error : Illegal characters in path.`

If i compare this file to the 2.4.1 one there are no differences.

**Comment by davidebbo** [comment]
That's quite puzzling if they are binary identical. Could something else be at play that's not directly related to this? It'd be interesting to go back and forth between the two version and and see if you consistently see it only with the newer one.

**Comment by tbertenshaw** [comment]
Hi @davidebbo , i edited my issue the original version was 2.4.1 not 2.4.2, which doesn't appear to exist.  I regressed the app to 2.4.3 and same error. However 2.4.1 (the version it was at before) works without errors. Wierd?

**Comment by davidebbo** [comment]
Actually, this is probably the same issue discussed on https://github.com/RazorGenerator/RazorGenerator/pull/90, which apparently was caused by the addition of VB support. Unfortunately, while two users reported this there, no one has been able to come forward with a repro repository. If you have one you can share, that would be helpful.

**Comment by pranavkm** [comment]
@tbertenshaw does it help if you disable vbhtml compilation. Try copying the contents from https://raw.githubusercontent.com/RazorGenerator/RazorGenerator/f97416361ca23a30246a57bf086d459702309273/RazorGenerator.MsBuild/RazorGenerator.MsBuild.targets to packages/RazorGenerator.MsBuild/build/RazorGenerator.MsBuild.targets and rebuilding

**Comment by tbertenshaw** [comment]
@pranavkm that code solves the compile error. (my MVC solution is c# incidentally).

I did spot another warning along with the original error (not sure if this also sheds light.)

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	MYWEBPROJECT		1	Active	To see what caused the issue, please try below.

1. Close Visual Studio
2. Open a Visual Studio Developer Command Prompt
3. Set environment variable “TraceDesignTime” to true (set TraceDesignTime=true)
4. Delete .vs directory/.suo file
5. Restart VS from the command prompt you set the environment varaible (devenv)
6. Open the solution
7. Check 'C:\Users\Administrator\AppData\Local\Temp\2\\MYWEBPROJECT_*.designtime.log' and look for the failed tasks (FAILED)
```

**Comment by pranavkm** [comment]
@tbertenshaw - seems like some sort of issue with Xamarin according to this SO post - http://stackoverflow.com/questions/36640315/vs-community-2015-xamarin-warningide0006error-encountered-while-loading-the-p

**Comment by kamsar** [comment]
I've got a very similar issue that I think I've figured out the cause.

* I have a `node_modules` in my solution like #3 
* I'm using cshtml
* After upgrading from 2.4.1 to 2.4.4 I'm getting illegal characters in path

This seems to be caused by the fact that I have no `.vbhtml` files in my project.
 
Given this in the msbuild targets file:
```
<RazorVbSrcFiles Condition=" '@(RazorVbSrcFiles)' == '' and '%(Extension)' == '.vbhtml' "
                Include="@(Content);@(None)" />
            <RazorVbSrcFiles Condition=" '@(RazorVbSrcFiles)' == '' "
                Include="**\*.vbhtml" />
```

The lack of presence of anything vb in the content or none item groups makes it fall through to the ` Include="**\*.vbhtml` which then scans all folders and finds the too long paths in my `node_modules` and you get illegal characters in path.

Make sense? As above, if I disable the VB support things work fine.

**Comment by pranavkm** [comment]
Thanks @kamsar for the fix. I'll get the fix published to NuGet.org shortly.

**Comment by pranavkm** [comment]
https://www.nuget.org/packages/RazorGenerator.MsBuild/2.4.5 is up on NuGet.

**Comment by kamsar** [comment]
That was fast!

Thank you :)

**Comment by mdrunk** [comment]
I'm new to actually participating in these, so please forgive me, but, isn't 2.4.5 already on NuGet?
